name: integrate
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Check cargo version
        run: cargo version
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
